[tool.ruff]
target-version = "py310"
line-length = 100
lint.select = ["ALL"]
lint.ignore = [
  "INP001", # File `...` is part of an implicit namespace package. Add an `__init__.py`.
  ]
lint.pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [

  "S",      # flake8-bandit
  "T201"    # `print` found
]

[tool.mypy]
ignore_missing_imports = true

[tool.pyright]
typeCheckingMode = "off"
reportPossiblyUnboundVariable = true
reportUnboundVariable = true
reportMissingImports = false
reportMissingModuleSource = false
reportInvalidTypeForm = false
