name: Tests

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md"]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    if: github.repository == 'RWTH-SpaMi/utilities'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv pip install --requirement requirements.txt --system
      - name: pytest
        run: |
          shopt -s globstar  # Enable recursive globbing
          pytest --nbmake **/*ipynb
